### ISSUE TITLE
How to save the predicted output from LayoutLM or LayoutLMv2 ?

### ISSUE THREAD

**Issue by karndeepsingh** [katanaml/sparrow#1]
I trained LayoutLM for my dataset and I am getting predictions at the word level like in the image "ALVARO FRANCISCO MONTOYA" is  true labeled as "party_name_1" but while prediction  "ALVARO " is tagged as "party_name_1", "FRANCISCO" is tagged as "party_name_1", "MONTOYA" is tagged as "party_name_1". In short, i am getting prediction for each word but how to save these prediction as one predicted output like "ALVARO FRANCISCO MONTOYA" as "party_name_1". How to save this as a single output?
Any help would be greatful.
Below image is the predicted output image from LayoutLM. 
![download (2) (2)](https://user-images.githubusercontent.com/49562460/160383498-67cccc0d-fb51-4153-bfcd-bd91bc7c7a02.png)

**Comment by abaranovskis-redsamurai** [comment]
Hi,

I think the easiest option would be to do the post-processing. Compare box coordinates for detected entities and group them, if they are close to each other.

Andrej

**Comment by karndeepsingh** [comment]
> Hi,
> 
> I think the easiest option would be to do the post-processing. Compare box coordinates for detected entities and group them, if they are close to each other.
> 
> Andrej

Thanks for Answering Andrej.
I tried to do. It is not working for all entities. If there are wrong predictions by the model, in that case this logic makes up the wrong assignment of the label. 
Please, help to make into required format.

Thanks

**Comment by abaranovskis-redsamurai** [comment]
May be you should do some preprocessing. When you get data from OCR, related words should be merged into a single phrase and sent as input to LayoutLMv2, this way model would learn a combination of words, not just single words. We don't have this functionality yet in Sparrow, that's why I can't help with the exact solution/answer.
