### ISSUE TITLE
Can you share google colab tutorial for it. Can it run on Korean langugage?

### ISSUE THREAD

**Issue by yhammadmufin** [katanaml/sparrow#10]
Can you share google colab tutorial for it. Can it run on Korean langugage?

**Comment by yhammadmufin** [comment]
@abaranovskis-redsamurai  Is it possible Can you please make a tutorial on Google Colab for the Korean language because most of my friends are interested in your work for the Korean language? It is very a great contribution if you add the Korean language to it. as I shared an image on another question too.

**Comment by abaranovskis-redsamurai** [comment]
Yes, I will do it later, not at this moment.
