### ISSUE TITLE
I have the following Image I want to apply this Repo on that Image 

### ISSUE THREAD

**Issue by yhammadmufin** [katanaml/sparrow#11]
I have the following Image I want to apply this Repo on that Image  Which is basically In Korean Language, 

Can you please share a google Colab tutorial for it?
![test_out](https://github.com/katanaml/sparrow/assets/129506205/d0427d2e-df90-47ba-9682-91fefff12b3e)

**Comment by abaranovskis-redsamurai** [comment]
#10 Seems like duplicate question
