### ISSUE TITLE
grouping annotations disappearing when changing some other annotation

### ISSUE THREAD

**Issue by dani-lu** [katanaml/sparrow#13]
I don't know if this just happen to me but when I do the grouping annotations under the ordering tab, if I come back to the mapping tab and I add another annotation or I simply change one of the existing annotations that I have then the whole group column under the ordering tab gets blank. 

This is annoying cause I have to be completely be sure that I will not add any more fields in the mapping tab or change any annotation before start making the groupings or I will have to group over and over for every change I make.

Also, this is a suggestion, it would be nice if you could group a bunch of annotations together in the ordering tab, right now you have to go one by one selecting in which group they belong, but if you have 50 of them that belong to the "summary" category for example, it would be better to select this 50 elements and group them into "summary" all at once, it would make the process much more faster.

thank you so much!

**Comment by abaranovskis-redsamurai** [comment]
This is how Streamlit (the framework I'm using for UI) makes a server call. Moving between tabs or selecting another annotation will reload the UI, and changes are lost. I recommend pressing Save, before going to another tab or selecting annotation. Save will store your changes in JSON so they will not be lost. Maybe I should add auto-save functionality.

Yes, your suggestion makes sense, I was thinking about this too. This is on my list of enhancements. Also, I plan to add more automation in the future, for example, some of the fields will be pre-populated with the labels (using OpenAI API).

**Comment by dani-lu** [comment]
I forgot to mentioned this, yes I saved multiple times under the ordering window to be sure that the groupings where saved and it keeps doing this behavior. Thats why I think its an issue, but I don't know if its just happening to me or to everybody, I changed the exporting function for it to group rows when a group finishes with "Items", like: Fees_Items, or Credits_Items, and so on, so that you don't have to create a group for each row like Item_1, Item_2, etc. But I don't know if this is creating the behavior I explained before, this is the function I changed, and I didn't change anything else:

 def export_labels(self, model):
        path_from = os.path.join("docs/json/")
        path_to = os.path.join("docs/json/key/")

        files = [f for f in os.listdir(path_from) if not f.startswith('.')]
        for file in files:
            path = os.path.join(path_from, file)
            if os.path.isfile(path):
                with open(path, "r") as f:
                    data = json.load(f)
                    words = data['words']

                    keys = {}

                    key_value_list = [[word['label'], word['value']] for word in words]
                    labels = set([word['label'] for word in words])
                    groups = set([label.split(':')[0] for label in labels])   
                    
                    result = {}
                    

                    for group in groups:
                        result[group] = []

                    for key, value in key_value_list:
                        category, subkey = key.split(':')
                        if category in result:
                            result[category].append((subkey, value))  
                            
                    label_dict = {}

                    for group in groups:
                        for label in labels:
                            if label.startswith(group + ':'):
                                label_dict[label.split(':')[1]] = group
                                
                    for group in groups: 
                        if 'Items' in group:
                            keys[group] = []
                            count = 0
                            item = {}
                            for element in result[group]:
                                for label in labels:
                                    if (label.split(':')[0] == group) and (element[0] == label.split(':')[1]):
                                        count =count+1
                                        item[element[0]] = element[1]
                                    if count == len([label.split(':')[1] for label in labels if label.startswith(group + ':')]):
                                        count=0
                                        keys[group].append(item)
                                        item = {}
                                        
                        else:
                            keys[group] = {}
                            for word in words:
                                for label in label_dict:
                                    if label_dict[word['label'].split(':')[1]] == group:
                                        keys[group][word['label'].split(':')[1]] = word['value']
                    
                    if keys != {}:
                        path = os.path.join(path_to, file)
                        with open(path, "w") as f:
                            json.dump(keys, f, indent=2)

So this function what it does is just appending an item to the groups that has "Items" in their name, and if they don't have, then it does the normal behavior and it just works if all the fields are labeled and grouped, so I don't see how this could affect what I just described above.

Thanks so much!

**Comment by abaranovskis-redsamurai** [comment]
Our team which does data annotation didnt faced the issue you describe. So, may be it is related to your change. Could you revert your change and try?

**Comment by dani-lu** [comment]
Yes, it's because of the change in this function. I don't really get why this function has anything to do with setting up all the groups, but I'll take a closer look at it. Thanks so much!

**Comment by abaranovskis-redsamurai** [comment]
Thanks for letting me know.
