### ISSUE TITLE
Error with training with cpu

### ISSUE THREAD

**Issue by ocrifydotnet** [katanaml/sparrow#14]
Error: AttributeError: 'DataLoader' object has no attribute '__code__'

I've updated trainer as below:

trainer = pl.Trainer(
        accelerator="cpu",#===========here
        devices=1,
        max_epochs=config_params.get("max_epochs"),
        val_check_interval=config_params.get("val_check_interval"),
        check_val_every_n_epoch=config_params.get("check_val_every_n_epoch"),
        gradient_clip_val=config_params.get("gradient_clip_val"),
        precision='bf16-mixed',  #===========here
        num_sanity_val_steps=0,
        # logger=wandb_logger,
        callbacks=[PushToHubCallback()],
    )

**Comment by abaranovskis-redsamurai** [comment]
Thanks for this. Does it work for you to fine-tune Donut model on CPU? For me on CPU it was never ending process, it only worked on GPU.

**Comment by ocrifydotnet** [comment]
It's still error on GPU. torch.cuda.is_available() returns True. I use ubuntu 22.4 run on wsl in my laptop. It's run ok on sparrow_finetuning_donut_v1.ipynb
