### ISSUE TITLE
Pandas v2 currently installed by default but throws error (for sparrow-ui)

### ISSUE THREAD

**Issue by MaxPowerWasTaken** [katanaml/sparrow#15]
Hello Andrej,

I'm a big fan of this repo, thanks for creating it! 

One issue I've encountered - for Sparrow-UI, after I install dependencies with `pip install -r requirements.txt` and then launch the data annotation UI with `streamlit run main.py`, I get the following error:
```
...
 File "/Users/max.epstein/opt/anaconda3/envs/spuienv/lib/python3.10/site-packages/st_aggrid/__init__.py", line 42, in __cast_date_columns_to_iso8601
    for c, d in dataframe.dtypes.iteritems():
  File "/Users/max.epstein/opt/anaconda3/envs/spuienv/lib/python3.10/site-packages/pandas/core/generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'iteritems'
```

[This SO answer notes](https://stackoverflow.com/a/76202088/1870832) that `Series.iteritems()` was removed as of Pandas v2. And while Pandas is not mentioned in your `requirements.txt` file, one of your dependencies seems to currently install Pandas v2 (as I can see from running `pip freeze | grep pandas` in my venv.

I fixed this issue by running `pip install "pandas<2.0"` after running `pip install -r requirements.txt`, but I'd suggest adding this line to requirements.txt as a better solution. Happy to provide a PR with just that change if you'd like as well.

**Comment by abaranovskis-redsamurai** [comment]
Hi Max, much appreciated for your time looking into this. If you could create a PR, this would be awesome :) Thanks!

**Comment by MaxPowerWasTaken** [comment]
Hi Andrej, PR submitted here: https://github.com/katanaml/sparrow/pull/16

Hopefully this is pretty straightforward but feel free to let me know if it's deficient in any way. I did test it manually by installing sparrow-ui requirements.txt in a fresh environment after making this change and then firing up `streamlit main.py` without errors.

**Comment by abaranovskis-redsamurai** [comment]
Thanks, I merged the change. Yes, works good :)
