### ISSUE TITLE
Configurable dataset location?

### ISSUE THREAD

**Issue by MaxPowerWasTaken** [katanaml/sparrow#19]
Hi Andrej,

Would you accept a PR to change all the paths with `/invoices/` in the sparrow-data code files to use a configurable `/dataset/` variable instead (to be set at the CLI and/or a config file)? I would keep the default value of `dataset` to be `invoice` so that default behavior of e.g. `run_ocr.py` would not change. 

That way, I could run sparrow-data functions on my own data/path with just a CLI change. Currently, in my local sparrow code I have updated those paths to something with `mydatasetname` in the code files, but then I can't keep pulling in your main updates because I will always have a conflict in the code with your paths which reference `/invoices/`.

**Comment by abaranovskis-redsamurai** [comment]
Hey, yes - this makes sense. Please add this functionality. Thanks!
