### ISSUE TITLE
LayoutLMv2 inference without labeling the new images

### ISSUE THREAD

**Issue by BhavanaMP** [katanaml/sparrow#2]
Hi @abaranovskis-redsamurai,

Could you provide me the  screenshot how the test data looks like before loading it to the model for inference?

I see that you are feeding the label information ['nertags'] as well during inference. When we are actually trying to predict the new image, how is it possible to give labels to them? Could you please throw some light on this?

Looking forward to your reply.

Thanks

**Comment by abaranovskis-redsamurai** [comment]
Hello,

True inference notebook (https://colab.research.google.com/drive/1g1b5gSaOr4awkILH6yOr1p1z2HrBPPNf?usp=sharing#scrollTo=8NuXZcEwUjh7) is using 'ner_tags', just to show correct results to compare with predicted results. Prediction is not using 'ner_tags'

You can see example of inference without any reference to the dataset in https://huggingface.co/spaces/katanaml/LayoutLMv2-CORD/blob/main/app.py

Regards,
Andrej

**Comment by BhavanaMP** [comment]
Thanks @abaranovskis-redsamurai for your inputs.
