### ISSUE TITLE
Issue while training the model.

### ISSUE THREAD

**Issue by AGRocky** [katanaml/sparrow#21]
Hi Folks, Greetings of the day to y'all. It is very commendable of the work that you have done and I highly appreciate the wok.
However, I found an error while running the training code on colab. I request the team to have a look into and get me the resolving steps. I am getting this error after running one epoch.
 Below is the error I am finding.

HfHubHTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/api/models/katanaml-org/invoices-donut-model-v1/commit/main (Request ID: Root=1-64c20bc3-1d8ccb5577b6df8a7e365802;055e011f-9ecd-4145-8055-394d9c223361)

Forbidden: pass `create_pr=1` as a query parameter to create a Pull Request

![Screenshot (69)](https://github.com/katanaml/sparrow/assets/90546817/b7919325-b02c-4277-b026-a741edaad47e)

**Comment by abaranovskis-redsamurai** [comment]
Hi.

I think you should replace katanaml-org with your account name here:

```
class PushToHubCallback(Callback):
    def on_train_epoch_end(self, trainer, pl_module):
        print(f"Pushing model to the hub, epoch {trainer.current_epoch}")
        pl_module.model.push_to_hub("katanaml-org/invoices-donut-model-v1",
                                    commit_message=f"Training in progress, epoch {trainer.current_epoch}")

    def on_train_end(self, trainer, pl_module):
        print(f"Pushing model to the hub after training")
        pl_module.processor.push_to_hub("katanaml-org/invoices-donut-model-v1",
                                    commit_message=f"Training done")
        pl_module.model.push_to_hub("katanaml-org/invoices-donut-model-v1",
                                    commit_message=f"Training done")
```

You was trying to commit files into our repo :)
