### ISSUE TITLE
How are annotations handled when training?

### ISSUE THREAD

**Issue by carlos21** [katanaml/sparrow#22]
I've been reading the code on `run_ocr.py`, `run_converter.py`, `run_donut.py` and it seems the dataset that gets uploaded to huggingface only contains the image + the json file in this format: (Also checked in huggingface and it only contains image + ground_truth it seems)

```
{
  "header": {
    "invoice_no": "40378170",
    "invoice_date": "10/15/2012",
    "seller": "Patel, Thompson and Montgomery 356 Kyle Vista New James, MA 46228",
    "client": "Jackson, Odonnell and Jackson 267 John Track Suite 841 Jenniferville, PA 98601",
    "seller_tax_id": "958-74-3511",
    "client_tax_id": "998-87-7723",
    "iban": "GB77WRBQ31965128414006"
  },
  "items": [
    {
      "item_desc": "Leed's Wine Companion Bottle Corkscrew Opener Gift Box Set with Foil Cutter",
      "item_qty": "1,00",
      "item_net_price": "7,50",
      "item_net_worth": "7,50",
      "item_vat": "10%",
      "item_gross_worth": "8,25"
    }
  ],
  "summary": {
    "total_net_worth": "$7,50",
    "total_vat": "$0,75",
    "total_gross_worth": "$8,25"
  }
}
```

So when the model needs to be trained, it only uses that data? What happens to the annotations and bounding boxes?

I recently started learning ML and I though annotations with bounding boxes needed to be part of the dataset. I would really appreciate some explanation on how it works.

Thanks a lot for your patience  🙂

**Comment by abaranovskis-redsamurai** [comment]
Thanks :) Answered here: https://www.youtube.com/watch?v=STmmFRUA40Y

Thats correct, bounding boxes are not required for Donut training. You only pass structured data and Donut internally is processing images, extracts text and matches text with your input for training.

Bounding boxes are not used. It is using only a text and annotation label to understand text type/class.
