### ISSUE TITLE
Is there a way to store the custom trained model locally and use it for inference?

### ISSUE THREAD

**Issue by carlos21** [katanaml/sparrow#23]
In the provided example you use `PushToHubCallback` to push the trained model to hugging face.

In my case, I just want to keep the model locally. I tried using `trainer.save_checkpoint("mymodel.ckpt")`. The file `mymodel.ckpt` gets saved but not sure how to use it for inference since in `sparrow_inference_donut_v1.ipynb` it uses the model directly from hugging face with:

```
processor = DonutProcessor.from_pretrained('katanaml-org/invoices-donut-model-v1')
model = VisionEncoderDecoderModel.from_pretrained('katanaml-org/invoices-donut-model-v1')
```

I tried providing the path to mymodel.ckpt but it doesn't work, it seems it's expecting to find these files:

<img width="277" alt="Screenshot 2023-08-05 at 02 25 37" src="https://github.com/katanaml/sparrow/assets/1591321/c0073fba-5a28-4abd-835c-45d100b662d8">

which I don't know to generate. Any help would be highly appreciated 🙂 thanks!

**Comment by accountsware** [comment]
check this https://huggingface.co/aliciatay/invoices-donut-katanaml/tree/main

**Comment by carlos21** [comment]
@accountsware I can see the files but is there a tutorial I can follow to know how to generate them?

**Comment by carlos21** [comment]
I was able to do it using 

```
pl_module.processor.save_pretrained(result_folder_path)
pl_module.model.save_pretrained(result_folder_path)
```

in PushToHubCallback
