### ISSUE TITLE
How to increase the accuracy after training a model?

### ISSUE THREAD

**Issue by carlos21** [katanaml/sparrow#24]
Hi everyone

I was able to create my fine-tuned model based on a dataset of 93 images. Here is an example:

Image:

![1106653](https://github.com/katanaml/sparrow/assets/1591321/281fd308-09ae-413b-8cc6-be493a4b3d30)

Json:
```
{
    "contractor_application_for_payment": {
        "original_contract_sum": "313,500.00",
        "net_change_by_change_orders": "0.00",
        "contract_sum_to_date": "313,500.00",
        "total_completed_and_stored_to_date": "100,000.00",
        "retainage": "10,000.00",
        "total_earned_less_retainage": "90,000.00",
        "less_previous_certificates_for_payment": "0.00",
        "current_payment_due": "90,000.00",
        "balance_to_finish": "223,500.00"
    }
}
```

Then I test how accurate my model is with 6 images and I get a poor result of 0.53 accuracy so not really sure what to do next.

For some documents, it's very inaccurate, it looks like it sets random values: (I'm just printing the values here)

```
Expected:
['16,875.00', '82,370.95', '99,245.95', '14,201.89', '1,420.19', '12,781.70', '0.00', '12,781.70', '86,464.25']

Inferred:
['16,875.00', '82,370.95', '99,245.95', '16,803.89', '1,639.18', '15,282.29', '0.00', '15,282.29', '60,442.22']
```

I'm basically using the same code as in this repo. Only my config is a bit different:

```
config = {
    "max_epochs": 30,
    "val_check_interval": 0.4,
    "check_val_every_n_epoch":1,
    "gradient_clip_val" :1.0,
    "num_training_samples_per_epoch": 93,
    "lr": 3e-5,
    "train_batch_sizes": [8],
    "val_batch_sizes": [1],
    # "seed":2022,
    "num_nodes": 1,
    "warmup_steps": 5,
    "result_path": "./result",
    "verbose": False,
}
```

Should I adjust it? or should I just train my model with a bigger dataset?

I'd appreciate some guidance please, thanks in advance!

**Comment by abaranovskis-redsamurai** [comment]
Based on my experience, 93 images are not enough. Should be around 400.
