### ISSUE TITLE
I see a bug on line #15 of pdf_converter.py file

### ISSUE THREAD

**Issue by rajans** [katanaml/sparrow#3]
# save the jpg file
            for page in pages:
                page.save(jpg_path + '/' + pdf_file.replace('.pdf', '') + '.jpg', 'JPEG')
                
This will overwrite with last page all the time. You may consider adding a counter initialized before the save loop and increment inside and add the counter to the name of the file to get separate file by page.

**Comment by abaranovskis-redsamurai** [comment]
Thanks, @rajans, good catch. At the moment, I test code only with single-page docs, I will keep it as is for now. I added a comment in the code, so as not to forget it in the future.

**Comment by MaxPowerWasTaken** [comment]
Hi Andrej,

I ran into this issue as well as I am using multi-page pdfs, so I've addressed this in my local branch. 

If you would be receptive to a PR with one change, that would just save images instead as:
 * [pdf_name_page_n.jpg] for n in 1..page-length (if page-length > 1), or
 * [pdf_name.jpg (current behavior)] if page-length==1

...I'd be happy to submit one. Obviously your call though. I'm a big fan of this repo and find your code very easy to work with, so I definitely appreciate your open-sourcing this!

**Comment by abaranovskis-redsamurai** [comment]
Hey Max, sure, please submit the change, I will merge it. Thanks a lot :)

**Comment by MaxPowerWasTaken** [comment]
PR submitted here: https://github.com/katanaml/sparrow/pull/18

**Comment by abaranovskis-redsamurai** [comment]
Thanks, the changes merged.
