### ISSUE TITLE
How to annotate new document image?

### ISSUE THREAD

**Issue by pfan-well** [katanaml/sparrow#30]
I tried to upload an image but I got this error. It's asking for a corresponding file in docs/json. 
But I haven't created one because I wish to use the annotation tool to do exactly that.
What are the steps to annotate new images? 
<img width="1466" alt="Screenshot 2023-12-19 at 3 20 19 PM" src="https://github.com/katanaml/sparrow/assets/147097992/da4f527f-4685-4b84-879b-8deee2de4d05">

**Comment by abaranovskis-redsamurai** [comment]
Hi.

When new image file is uploaded, empty JSON for annotations is automatically created under docs/json. Try to debug function upload_file from data_annotation.py. See line related to "with open(os.path.join("docs/json/", file_name + ".json"), "w") as f:". Check if this file is created on your environment.

Regards,
Andrej

**Comment by pfan-well** [comment]
I see. I put the image in the docs/images first which now I realized is wrong. I uploaded it from the UI then select it in the drop-down menu and it worked. Another question- my document image got cut off in the UI- is there a dimension requirement I should resize it to? Thank you very much.

**Comment by abaranovskis-redsamurai** [comment]
If you close the menu group sidebar, the image should be correctly displayed - as there will be more horizontal space. Width is calculated in main.py, check option2 for annotation UI. You can adjust the width calculation if it doesn't work for your type of image.
