### ISSUE TITLE
Can you share google Colab code for this Repo

### ISSUE THREAD

**Issue by yhammadmufin** [katanaml/sparrow#33]
Hello, I hope you are doing well. I want to run this repo on Google colab. How Can I run this

**Comment by abaranovskis-redsamurai** [comment]
Sparrow is not just a single app that you can directly run, Sparrow is based on services - Donut Data, Donut ML, UI for Donut, LLM ML. Which part you want to run?

**Comment by yhammadmufin** [comment]
@abaranovskis-redsamurai  i want to run the OCR service on the following Image
![image (2)](https://github.com/katanaml/sparrow/assets/129506205/f4171caa-1daa-454b-89f1-761216f9a954)
