### ISSUE TITLE
Error with docker

### ISSUE THREAD

**Issue by svenbjornkvilt** [katanaml/sparrow#39]
Getting error {"action":"startup","error":"invalid config: no authentication scheme configured, you must select at least one","level":"error","msg":"could not load config","time":"2024-03-01T08:58:45Z"}
 When to start the docker.

**Comment by Asif-droid** [comment]
when running on docker hitting api:  /api/v1/sparrow-llm/ingest
having internal server error for this:
 weaviate.exceptions.WeaviateStartUpError: Weaviate did not start up in 5 seconds. Either the Weaviate URL http://localhost:8080 is wrong or Weaviate did not start up in the interval given in 'startup_period'
 
I have started the weaviate-db container:
curl localhost:8080
{"links":{"href":"/v1","name":"api v1","documentationHref":"https://weaviate.io/developers/weaviate/current/"}}

help me to resolve this.
