### ISSUE TITLE
What to do after annotation?

### ISSUE THREAD

**Issue by shrey6996** [katanaml/sparrow#4]
I am performing the following steps:

1.) Deleted all the pdf, images and json from all the folders. I only kept 5 pdf files in the "sparrow-data/docs/input/invoices/Dataset with valid information" folder in order to test the training process.
1.) Installed the all the relevent libraries in the **sparrow-data** and **sparrow-ui** folder.
2.) Ran **run_ocr.py** and **run_converter.py** in order to get processed json in "sparrow-data/docs/input/invoices/processed/output" folder.
3.) Copied the json files from "sparrow-data/docs/input/invoices/processed/output" to "sparrow-ui/docs/json" folder.
4.) Annotated the documents by running the streamlit app and exported the labels.

After this step what should I do next? I watched the 3 tutorials on how to prepare the dataset using sparrow annotation tool but I couldn't find instruction on what to do after annotations. If I run **run_donut.py** I get an error that metadata.jsonl file is empty. The training, validation and testing folders present in the sparrow-data folder are also empty except for a jsonl file which is again empty. Kindly guide me in the right direction!

Thanks in advance!

**Comment by abaranovskis-redsamurai** [comment]
hey, thanks a lot for a detailed question.

I plan to automate/improve file transfer between services.

What you should do:

1. Go to sparrow-data/docs/models/donut/data and copy your annotated JSON files into **key** folder (check an example, images are inside img folder)
2. Delete all files from data/img/test, train, and validation folders, respectively. Keep folders
3. Run run_donut.py, you should see images in train, validation and test folders. There will be one jsonl file per folder
4. Run python run_donut_upload.py to upload dataset to your Hugging Face infra

Next you can go to sparrow-ml and run v1 notebooks, dataset will be used directly from Hugging Face. Keep in mind v2 notebooks are using different data preparation approach and for that reason data is copied into **data** folder, but for v1 notebooks this data is not needed.
