### ISSUE TITLE
api/chat not available

### ISSUE THREAD

**Issue by svenbjornkvilt** [katanaml/sparrow#40]
HTTPStatusError: Client error '404 Not Found' for url 'http://127.0.0.1:11434/api/chat'
![image](https://github.com/katanaml/sparrow/assets/146725746/9adfb55b-9824-4792-a0ba-71a8f1fe8ea4)

**Comment by abaranovskis-redsamurai** [comment]
This means either Ollama is not installed or problem with Ollama install.

**Comment by DrewThomasson** [comment]
i have that issue but I can verify that ollama is fully installed and working on my system

the `ollama run llama3` command works as expectedgiving me a terminal chat,

and also using curl shows that it exists on my machine

`(.env_llamaindex) (base) drew@drew-System-Product-Name:~/sparrow/sparrow-ml/llm$ curl http://127.0.0.1:11434/api/chat -d '{
  "model": "llama3",
  "prompt": "Why is the sky blue?"
}'
{"model":"llama3","created_at":"2024-05-08T01:51:47.34946244Z","message":{"role":"assistant","content":""},"done":true}(.env_llamaindex) (base) drew@drew-System-Product-Name:~/sparrow/sparrow-ml/llm$ 
`

This works giving me some response as you can see, and not just the 404 error

**Comment by DrewThomasson** [comment]
> HTTPStatusError: Client error '404 Not Found' for url 'http://127.0.0.1:11434/api/chat' ![image](https://private-user-images.githubusercontent.com/146725746/309231637-9adfb55b-9824-4792-a0ba-71a8f1fe8ea4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMzY4OTUsIm5iZiI6MTcxNTEzNjU5NSwicGF0aCI6Ii8xNDY3MjU3NDYvMzA5MjMxNjM3LTlhZGZiNTViLTk4MjQtNDc5Mi1hMGJhLTcxYThmMWZlOGVhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOFQwMjQ5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTBlOGI2NWFkNDA5NjBiMWYxOGE2ODgzMjcyMzczMDMzY2IyODFjZTM3NTI3YjQ3MDdjZjM4NTY0OGNjODgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8tFuJr3z-Yrtp3b48jBC0Hk7kmeFwVbbm-ObLOF9rok)

did you manage to ever fix this issue on your end?

**Comment by abaranovskis-redsamurai** [comment]
In LlamaIndex agent, call to Ollama is made in script: https://github.com/katanaml/sparrow/blob/main/sparrow-ml/llm/rag/agents/llamaindex/llamaindex.py

Check this line:

```
llm = self.invoke_pipeline_step(lambda: Ollama(model=cfg.LLM, base_url=cfg.OLLAMA_BASE_URL, temperature=0,
                                                       request_timeout=900),
                                        "Loading Ollama...",
                                        local)
```

You can create new basic Python script and try to call Ollama from there, to troubleshoot the issue:

```
Ollama(model=cfg.LLM, base_url=cfg.OLLAMA_BASE_URL, temperature=0,
                                                       request_timeout=900)
```

See if it works or no.

**Comment by DrewThomasson** [comment]
Never mind I fixed it you were right i just didn't have it set up correctly

I just hand't downloaded the specific model that the config.yml had set

running 

`ollama run adrienbrault/nous-hermes2pro:Q5_K_M-json`

or 

`ollama run llama3:8b-instruct-q5_K_M`


fixed the issue I was having

**Comment by Asif-droid** [comment]
when running on docker hitting api: /api/v1/sparrow-llm/ingest
having internal server error for this:
weaviate.exceptions.WeaviateStartUpError: Weaviate did not start up in 5 seconds. Either the Weaviate URL http://localhost:8080/ is wrong or Weaviate did not start up in the interval given in 'startup_period'

I have started the weaviate-db container:
curl localhost:8080
{"links":{"href":"/v1","name":"api v1","documentationHref":"[https://weaviate.io/developers/weaviate/current/"}}](https://weaviate.io/developers/weaviate/current/%22%7D%7D)

help me to resolve this.
