### ISSUE TITLE
Installation Tutorial

### ISSUE THREAD

**Issue by geeksq** [katanaml/sparrow#41]
Is there a step by step installation tutorial?

I tried this installation on an Ubuntu 22.04 following https://github.com/katanaml/sparrow/blob/main/README.MD

Once i reached LLM:
`./sparrow.sh ingest`

I get : 
`Missing option '--file-path'.`

But if i supplied path with the sample data, 
`./sparrow.sh ingest --file-path data/invoice_1.pdf`

I get: 
```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/llm/sparrow/sparrow-ml/llm/ingest.py:14 in run                                       │
│                                                                                                  │
│   11 def run(file_path: Annotated[str, typer.Option(help="The file to process")],                │
│   12 │   │   agent: Annotated[str, typer.Option(help="Ingest agent")] = "llamaindex"):           │
│   13 │   user_selected_agent = agent  # Modify this as needed                                    │
│ ❱ 14 │   ingest = get_ingest(user_selected_agent)      
...< and alot of codes>...
AttributeError: module 'threadpoolctl' has no attribute 'threadpool_limits'
```

**Comment by abaranovskis-redsamurai** [comment]
hey. im adding now file-path support and soon will update readme. But in your case, it seems some sort of libs setup issue, related to threadpoolctl. I havent tested it on Ubuntu.
