### ISSUE TITLE
http connection error while using vprocessor

### ISSUE THREAD

**Issue by nehashinde-canopy** [katanaml/sparrow#44]
I am getting following error when I use vprocessor: 

ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=8001): Max retries 
exceeded with url: /api/v1/sparrow-ocr/inference (Caused by 
NewConnectionError('<urllib3.connection.HTTPConnection object at 
0x71e175f92d10>: Failed to establish a new connection: [Errno 111] Connection 
refused'))

**Comment by abaranovskis-redsamurai** [comment]
You need to start Sparrow OCR service, check README.

**Comment by tribiona** [comment]
Please help me start the OCR service. I am not able to start it. The readme is not clear on how to start the service.
