### ISSUE TITLE
Have you seen this issue while installing requirements.txt of sparrow-ocr?

### ISSUE THREAD

**Issue by tribiona** [katanaml/sparrow#46]
Collecting python-poppler==0.4.1
  Using cached python_poppler-0.4.1.tar.gz (138 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 156, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'mesonpy' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 160, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-qqwjak5s/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 985, in wrapper
          return func(*args, **kwargs)
        File "/tmp/pip-build-env-qqwjak5s/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 1038, in build_wheel
          with _project(config_settings) as project:
        File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
          return next(self.gen)
        File "/tmp/pip-build-env-qqwjak5s/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 912, in _project
          yield Project(source_dir, build_dir, meson_args, editable_verbose)
        File "/tmp/pip-build-env-qqwjak5s/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 635, in __init__
          self._meson = _get_meson_command(pyproject_config.get('meson'))
        File "/tmp/pip-build-env-qqwjak5s/overlay/local/lib/python3.10/dist-packages/mesonpy/__init__.py", line 947, in _get_meson_command
          meson_version = subprocess.run(cmd + ['--version'], check=False, text=True, capture_output=True).stdout
        File "/usr/lib/python3.10/subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'meson'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by abaranovskis-redsamurai** [comment]
Nope, it installs fine on my environment, macOS. Customers were installing it on Windows and Linux without issues.

**Comment by XzAeRo** [comment]
Make sure your pip version is updated. This may happen on default python installs.

**Comment by tribiona** [comment]
> Make sure your pip version is updated. This may happen on default python installs.

Thanks it solved the error. Now getting this error:

Collecting python-poppler==0.4.1 (from -r requirements.txt (line 8))
  Using cached python_poppler-0.4.1.tar.gz (138 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      + meson setup /tmp/pip-install-_wz1kmq2/python-poppler_e920fe8337e44ab7bd0caefc28a6bbda /tmp/pip-install-_wz1kmq2/python-poppler_e920fe8337e44ab7bd0caefc28a6bbda/.mesonpy-0i_9ayak -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/tmp/pip-install-_wz1kmq2/python-poppler_e920fe8337e44ab7bd0caefc28a6bbda/.mesonpy-0i_9ayak/meson-python-native-file.ini
      The Meson build system
      Version: 1.4.0
      Source dir: /tmp/pip-install-_wz1kmq2/python-poppler_e920fe8337e44ab7bd0caefc28a6bbda
      Build dir: /tmp/pip-install-_wz1kmq2/python-poppler_e920fe8337e44ab7bd0caefc28a6bbda/.mesonpy-0i_9ayak
      Build type: native build
      Project name: python-poppler
      Project version: 0.4.1
      C++ compiler for the host machine: c++ (gcc 11.4.0 "c++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
      C++ linker for the host machine: c++ ld.bfd 2.38
      Host machine cpu family: x86_64
      Host machine cpu: x86_64
      Found pkg-config: YES (/usr/bin/pkg-config) 0.29.2
      Did not find CMake 'cmake'
      Found CMake: NO
      Run-time dependency poppler-cpp found: NO (tried pkgconfig)
      
      ../meson.build:11:14: ERROR: Dependency "poppler-cpp" not found, tried pkgconfig
      
      A full log can be found at /tmp/pip-install-_wz1kmq2/python-poppler_e920fe8337e44ab7bd0caefc28a6bbda/.mesonpy-0i_9ayak/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by tribiona** [comment]
Solved using:

!apt-get install poppler-utils libpoppler-cpp-dev
!pip install -v -v python-poppler

**Comment by abaranovskis-redsamurai** [comment]
I updated readme for OCR to include your findings, thanks.

**Comment by imweijh** [comment]
on macOS need:
`brew install poppler`

**Comment by abaranovskis-redsamurai** [comment]
I updated readme and included this info into requirements files.
