### ISSUE TITLE
Model assuming NoneType instead of string.

### ISSUE THREAD

**Issue by tribiona** [katanaml/sparrow#48]
![unnamed](https://github.com/katanaml/sparrow/assets/164365168/e3526889-b7f1-4671-9540-86caa049c0ab)
I am using gemma-7b model. I am getting this error for the above pdf:

ws_nm_ncqa_recred_oe_batch_desc
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
other_specialities
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
upin_number
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type
taxonomy_code
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.6/v/string_type

Looks like wherever the output value in the document is None or No information provided, the model is assuming NoneType but I cannot give NoneType as type in the command as I won't know in advance which fields would be none. Is there a way the model could ignore such fields. Sme change in prompts? Or any other solution to this problem?

**Comment by abaranovskis-redsamurai** [comment]
Gemma is quite bad in data extraction. Use either Starling or adrienbrault/nous-hermes2pro:Q5_K_M-json as per config

**Comment by tribiona** [comment]
I need a model for commercial use.

**Comment by abaranovskis-redsamurai** [comment]
https://huggingface.co/NousResearch/Hermes-2-Pro-Mistral-7B comes with Apache license, it means available for commercial use.

**Comment by tribiona** [comment]
Is it the same as adrienbrault/nous-hermes2pro:Q5_K_M-json ?
