### ISSUE TITLE
Haystack giving timeout error

### ISSUE THREAD

**Issue by tribiona** [katanaml/sparrow#49]
At the ingest step haystack agent is throwing timeout error. I just ran the command:
./sparrow.sh ingest --file-path /data/invoice_1.pdf --agent haystack --index-name Sparrow_haystack_doc1

Error:
ReadTimeout: HTTPConnectionPool(host='127.0.0.1', port=11434): Read timed out. (read timeout=120)

**Comment by abaranovskis-redsamurai** [comment]
This means your machine is too slow, not using GPU
