### ISSUE TITLE
ModuleNotFoundError: No module named 'rapidfuzz.string_metric'

### ISSUE THREAD

**Issue by shrey10926** [katanaml/sparrow#5]
Hi. I am getting the error `ModuleNotFoundError: No module named 'rapidfuzz.string_metric'` when executing the following command `python run_ocr.py`. 

I have installed the requirements before running the command. Also I have separately install rapidfuzz using `pip install rapidfuzz` but still getting the error. My python version is 3.8.0.
Any help is appreciated!

Thanks in advavce!

**Comment by abaranovskis-redsamurai** [comment]
Hi, you don't need to install this library, the install list from requirements should be enough. I'm running it on Python 3.7. Could you give it a try with version 3.7 if you can?

**Comment by shrey10926** [comment]
I know the library is not listed in the requirements.txt. Even if I do not install it separately, I am still getting the error.

Also I tried with python 3.7 and now a different error occurs:

`OSError: cannot load library 'gobject-2.0-0': gobject-2.0-0: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'gobject-2.0-0'`

**Comment by shrey10926** [comment]
Yes rapidfuzz is getting installed through dependencies. Also my torch version is the same as yours since I am installing all the libraries through requirements.txt present in the repo.

But I finally found the solution. I was using the repo 3 weeks back and this error was not coming. Only today when I did a fresh installation did the error occur. 

This is because rapidfuzz was upgraded from 2.15.1 (which was the version getting installed when we install requirements.txt) to 3.0.0 (which is the updated version updated 2 weeks back). 

rapidfuzz 2.15.1 works fine but for 3.0.0 the above error occurs.

**Comment by shrey10926** [comment]
@abaranovskis-redsamurai  I would like to contribute to your repo. Currently we have to move the json file and images from `sparrow-data` to `sparrow-ui` manually. Can I work on automating that?

**Comment by abaranovskis-redsamurai** [comment]
> Yes rapidfuzz is getting installed through dependencies. Also my torch version is the same as yours since I am installing all the libraries through requirements.txt present in the repo.
> 
> But I finally found the solution. I was using the repo 3 weeks back and this error was not coming. Only today when I did a fresh installation did the error occur.
> 
> This is because rapidfuzz was upgraded from 2.15.1 (which was the version getting installed when we install requirements.txt) to 3.0.0 (which is the updated version updated 2 weeks back). So now whenever we install requirements.txt, the upgraded version of rapidfuzz (3.0.0 which does not support `rapidfuzz.string_metric`) will get installed and we will get the above error!
> 
> rapidfuzz 2.15.1 works fine but for 3.0.0 the above error occurs.

Perfect, thanks for letting me know. Will keep it in mind.

**Comment by abaranovskis-redsamurai** [comment]
> @abaranovskis-redsamurai I would like to contribute to your repo. Currently we have to move the json file and images from `sparrow-data` to `sparrow-ui` manually. Can I work on automating that?

Thanks a lot, this is very much appreciated :) This was on my task list. I saw your pull request, will review it next week and merge the code.
