### ISSUE TITLE
License and usage clarification

### ISSUE THREAD

**Issue by schewara** [katanaml/sparrow#51]
I just came across this promising project but the license and usage needs clarification.

- The [LICENSE](https://github.com/katanaml/sparrow/blob/main/LICENSE) in the repo is GPL
- The [License Section](https://github.com/katanaml/sparrow/tree/main#license) in the README says it's under the Apache License
- And the [Commercial usage](https://github.com/katanaml/sparrow?tab=readme-ov-file#commercial-usage) section in the README and the mentioning of dual licensing options add even more confusion to it.

To be able to consider evaluating this project for potential uses, this needs to be sorted out.

Also considering the latest licensing change Headlines around Redis it would be good to be transparent about potential future plans around licensing.

Once the confusion about the Licensing is resolved, we can move on to having an actual look at sparrow itself.

**Comment by abaranovskis-redsamurai** [comment]
Hello. I fixed license section to GPL 3.0, Apache was a mistype. Also I updated and explained in more detail commercial usage section. Thanks for your question.

**Comment by schewara** [comment]
Outstanding and thanks for the swift update. :heart:
