### ISSUE TITLE
Getting Errors while running sparrow.sh under llm

### ISSUE THREAD

**Issue by sanjay-nit** [katanaml/sparrow#54]
I already installed all dependencies, Looks like there are some version conflicts.

FYI: I'm running it on Linux(Ubuntu 22.04.1)

Issues: ModuleNotFoundError: No module named 'tenacity.asyncio'

**Comment by abaranovskis-redsamurai** [comment]
hey, which agent you are trying to run?

**Comment by sanjay-nit** [comment]
> hey, which agent you are trying to run?

I've installed Ollama and pulled llama3 model.

**Comment by abaranovskis-redsamurai** [comment]
yes, but how you are running Sparrow, which command you are executing, before getting that error?
