### ISSUE TITLE
Validation Error

### ISSUE THREAD

**Issue by Sumeet213** [katanaml/sparrow#61]
ValidationError(
    model='DynamicModel',
    errors=[
        {
            'loc': ('__root__',),
            'msg': 'Expecting value: line 1 column 1 (char 0)',
            'type': 'value_error.jsondecode',
            'ctx': {
                'msg': 'Expecting value',
                'doc': 'Empty Response',
                'pos': 0,
                'lineno': 1,
                'colno': 1
            }
        }
    ]
    
    Llama index with this LLM: 'adrienbrault/nous-hermes2theta-llama3-8b:q5_K_M' keep getting this error

**Comment by abaranovskis-redsamurai** [comment]
not reproduced
