### ISSUE TITLE
Seeking Help to run the service in docker 

### ISSUE THREAD

**Issue by Asif-droid** [katanaml/sparrow#62]
I used this docker file to run the llamaindex service :

 FROM pytorch/pytorch:2.3.0-cuda12.1-cudnn8-devel

 WORKDIR /app

 COPY requirements.txt requirements.txt

 RUN pip install --no-cache-dir -r requirements.txt

 RUN apt-get update && apt-get install -y libgl1-mesa-glx

 RUN apt-get update && apt-get install -y libglib2.0-0

 COPY . .

 EXPOSE 5800

 CMD ["bash"]

but having the error python version 3.10.4 is needed . current version is 3.10.14 

anyone plz help me run this service on docker.....

**Comment by abaranovskis-redsamurai** [comment]
I havent tested running in Docker.
