### ISSUE TITLE
Error: `llama-index-readers-file` package not found despite being installed

### ISSUE THREAD

**Issue by albertgilopez** [katanaml/sparrow#64]
I'm encountering an error when trying to use the `SimpleDirectoryReader` from LlamaIndex in my project. The error message states that the `llama-index-readers-file` package is not found, even though it's installed.

## Environment

- LlamaIndex version: 0.10.23
- llama-index-readers-file version: 0.1.12
- Python version: 3.10.14
- Operating System: Microsoft Windows 11 Pro

## Project Structure

sparrow-ml/
├── llm/
│ ├── rag/
│ │ └── agents/
│ │ └── llamaindex/
│ │ ├── llamaindex.py
│ │ ├── vllamaindex.py
│ │ └── vprocessor.py
│ ├── api.py
│ ├── ingest.py
│ └── requirements_llamaindex.txt

## Steps to Reproduce

0. Create .env_llamaindex environment

1. Install LlamaIndex and its dependencies:
   ```
   pip install -r sparrow-ml/llm/requirements_llamaindex.txt
   ```
2. Run the FastAPI application:
   ```
   python sparrow-ml/llm/api.py
   ```
3. Attempt to perform document ingestion through the API endpoint.

## Error Message

unning ingest with llamaindex
⠋ Connecting to Weaviate...
[Weaviate connection logs omitted for brevity]
⠼ Connecting to Weaviate...
⠋ Loading documents...
ERROR:root:Unexpected error occurred: llama-index-readers-file package not found
ERROR:api:ValueError in ingest: Unexpected error: llama-index-readers-file package not found
INFO: 127.0.0.1:51045 - "POST /api/v1/sparrow-llm/ingest HTTP/1.1" 400 Bad Request

## Additional Context

- The error occurs specifically when trying to load documents, likely in the `ingest.py` file.
- I've verified that `llama-index-readers-file` is installed using `pip list`.
- I've tried creating a new virtual environment and reinstalling all dependencies.
- The error persists even after following the migration guide for v0.10.

## Questions

1. Is there a known issue with `llama-index-readers-file` in version 0.10.23?
2. Are there any additional steps or configurations needed to properly use `SimpleDirectoryReader` in this version, especially considering our project structure?
3. Could this be related to how the package is being imported or used in our `ingest.py` file?
4. Are there any specific changes needed in our `llamaindex.py` or `vllamaindex.py` files to accommodate the new structure in LlamaIndex v0.10?

Any assistance or guidance on resolving this issue would be greatly appreciated. Thank you for your time and support.

**Comment by abaranovskis-redsamurai** [comment]
Hi, code is tested on macOS platform and all works fine with currently listed versions. You are trying to run it through API, try to run directly through CLI and check if same issues appears.

**Comment by raininja** [comment]
I have this same problem, I was able to hack around it by commenting out the PandasExeclReader references in llama_index/core/readers/file/base.py.  Evidently there is an upstream issue in llama_index causing this https://github.com/run-llama/llama_index/discussions/11604 .
