### ISSUE TITLE
Running sparrow.sh ingest  doesn't result in anything

### ISSUE THREAD

**Issue by Wavefunction-collapse** [katanaml/sparrow#65]
Hello ! Thank you for this awesome repo !
I have problem iwht it, namely: Running sparrow.sh ingest --file-path /data/invoice_1.pdf --agent llamaindex --index-name Sparrow_llamaindex_doc1 doesn't result in anything or 
sparrow.sh "invoice_number, invoice_date, client_name, client_address, client_tax_id, seller_name, seller_address,seller_tax_id, iban, names_of_invoice_items, gross_worth_of_invoice_items, total_gross_worth" "int, str, str, str, str,str, str, str, str, List[str], List[float], str" --agent llamaindex --index-name Sparrow_llamaindex_doc1

doesn't result in anything. I see a Git bash opening for two seconds (no idea why?) and that is it. I think my installation is successful. Any advice would be appreciated.

**Comment by abaranovskis-redsamurai** [comment]
Hey. try to run inference task and see if it is producing any result:

./sparrow.sh "invoice_number, invoice_date, client_name, client_address, client_tax_id, seller_name, seller_address,
seller_tax_id, iban, names_of_invoice_items, gross_worth_of_invoice_items, total_gross_worth" "int, str, str, str, str,
str, str, str, str, List[str], List[float], str" --agent llamaindex --index-name Sparrow_llamaindex_doc1

**Comment by Wavefunction-collapse** [comment]
It is also not producing any results. Important note I forgot: I am using sparrow.sh"..." and not ./sparrow.sh, because I am inside an anaconda enviroment. I installed most of the stuff using WSL.

**Comment by jfbvm** [comment]
Hi @Wavefunction-collapse , I sugest you to not use WSL, it doesn't have all compatibility that real Linux installation have, trust me, I've been through this...
My suggestion, run a virtual Linux machine and try again.
