### ISSUE TITLE
Sparrow parse model repository not found

### ISSUE THREAD

**Issue by SalvadorRuizGuevara** [katanaml/sparrow#73]
When im trying to use the sparrow-parse agent it gives the following error:

> huggingface_hub.errors.RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-67004a09-066d8f903d8c88d071f3c213;b02687c7-fa52-4c92-8120-36baf4e06e1d)
> 
> Repository Not Found for url: https://huggingface.co/api/spaces/katanaml/sparrow-qwen2-vl-7b.
> Please make sure you specified the correct `repo_id` and `repo_type`.
> If you are trying to access a private or gated repo, make sure you are authenticated.

Is the sparrow parse model deprecated? Or moved to another repository?

**Comment by abaranovskis-redsamurai** [comment]
This is correct, this HF space is private, as it runs on paid GPU. You can create your own HF space and deploy the code available in Sparrow Parse: https://github.com/katanaml/sparrow/tree/main/sparrow-data/parse/sparrow_parse/vllm/infra/qwen2_vl_7b

**Comment by mrtj** [comment]
May I suggest to update the [documentation](https://github.com/katanaml/sparrow/tree/main/sparrow-data/parse) with this info? I really struggle to get anything working in this repo, out of the unstructured wrapper. What is "sparrow key" for example?

**Comment by abaranovskis-redsamurai** [comment]
I'm in the process of updating and simplifying docs structure currently. In the next version agents and code related to Unstructured, Haystack, LlamaIndex and LangChain will be removed. As my primary focus on Sparrow Parse functionality with vision LLM models. Sparrow Parse generates the best results with vision LLM.

Sparrow key can be set to anything in your own deployment. I use Sparrow key to control access to Sparrow deployment on GPU instance, for example: https://katanaml-sparrow-ui.hf.space. I give Sparrow key only to potential customers.
