### ISSUE TITLE
Huggingface repository not found

### ISSUE THREAD

**Issue by Julm** [katanaml/sparrow#75]
When running Sparrow as following, with environment variable HF_TOKEN set,

`./sparrow.sh '[{"instrument_name":"string", "valuation":0}]' --agent "sparrow-parse" --debug --options huggingface --options Qwen/Qwen2-VL-7B-Instruct  --file-path "/data/bonds_table.png"
`

I get the following error

```
RepositoryNotFoundError: 404 Client Error. (Request ID: Root=1-6735be4a-28fcea832439ef725b93f7c3;903ed964-93f5-4606-a557-2f261b9d3e4f)

Repository Not Found for url: https://huggingface.co/api/spaces/Qwen/Qwen2-VL-7B-Instruct.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated.
```

Could you tell me what I'm missing?
Thanks

**Comment by abaranovskis-redsamurai** [comment]
Hi, I updated readme:

```
GPU backend `katanaml/sparrow-qwen2-vl-7b` is private, to be able to run below command, you need to create your own backend on Hugging Face space using [code](https://github.com/katanaml/sparrow/tree/main/sparrow-data/parse/sparrow_parse/vllm/infra/qwen2_vl_7b) from Sparrow Parse.
```

At the moment Visual LLM backend runs only on cloud GPU, work in progress to make it run on local Apple MLX backend. If you have Nvidia server, then you can deploy it on Nvidia.
