### ISSUE TITLE
TypeError: 'ModelConfig' object is not subscriptable

### ISSUE THREAD

**Issue by anudwigna** [katanaml/sparrow#78]
Here is my request:

```
curl -X 'POST' \
  'http://localhost:8000/api/v1/sparrow-llm/inference' \
  -H 'accept: application/json' \
  -H 'Content-Type: multipart/form-data' \
  -F 'query=[{"instrument":"str","valuation":0}]' \
  -F 'agent=sparrow-parse' \
  -F 'options=mlx,mlx-community/Qwen2-VL-7B-Instruct-4bit' \
  -F 'debug_dir=string' \
  -F 'debug=false' \
  -F 'sparrow_key=' \
  -F 'file=@bonds_table.png;type=image/png'
```
  
The error I am getting after the API Call is: 
**TypeError: 'ModelConfig' object is not subscriptable**

**Comment by abaranovskis-redsamurai** [comment]
Hey,

Do you have stack trace printed? Also debug_dir must be empty or valid path.

Andrej

**Comment by preethisenthil27** [comment]
when i run python -m sparrow_parse.extractors.vllm_extractor

im facing this issue

root@cw-ai-gpu-01:/app/new_sparrow/sparrow/sparrow-data/parse# python -m sparrow_parse.extractors.vllm_extractor
MLXInference initialized with model: mlx-community/Qwen2-VL-72B-Instruct-4bit
Input data:
[
    {
        'file_path': '/app/new_sparrow/sparrow/sparrow-data/Pdf/finalcial_doc.pdf',
        'text_input': 'retrieve document data. return response in JSON format'
    }
]
Processing 6 pages for table extraction.
Loading table detection model...
Table detection model initialized.
Preparing image for table detection...
Identifying tables in the image...
Cropping tables from the image...
Table detected in: /tmp/tmp0igfotwi/finalcial_doc_page_1.jpg - 1
Table detected in: /tmp/tmp0igfotwi/finalcial_doc_page_1.jpg - 2
Table detected in: /tmp/tmp0igfotwi/finalcial_doc_page_1.jpg - 3
Table detected in: /tmp/tmp0igfotwi/finalcial_doc_page_1.jpg - 4
Table detected in: /tmp/tmp0igfotwi/finalcial_doc_page_1.jpg - 5
Processing page_1_table_1 for document /tmp/tmp0igfotwi/finalcial_doc_page_1.jpg
Fetching 18 files: 100%|███████████████████████████████████████████████████████| 18/18 [00:00<00:00, 3762.08it/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/new_sparrow/sparrow/sparrow-data/parse/sparrow_parse/extractors/vllm_extractor.py", line 177, in <module>
    results_array, num_pages = extractor.run_inference(model_inference_instance, input_data, tables_only=True,
  File "/app/new_sparrow/sparrow/sparrow-data/parse/sparrow_parse/extractors/vllm_extractor.py", line 30, in run_inference
    return self._process_pdf(model_inference_instance, input_data, tables_only, debug, debug_dir, mode)
  File "/app/new_sparrow/sparrow/sparrow-data/parse/sparrow_parse/extractors/vllm_extractor.py", line 43, in _process_pdf
    results = self._process_pages(model_inference_instance, output_files, input_data, tables_only, debug, debug_dir)
  File "/app/new_sparrow/sparrow/sparrow-data/parse/sparrow_parse/extractors/vllm_extractor.py", line 84, in _process_pages
    tables_result = self._extract_tables(
  File "/app/new_sparrow/sparrow/sparrow-data/parse/sparrow_parse/extractors/vllm_extractor.py", line 117, in _extract_tables
    result = self._run_model_inference(model_inference_instance, input_data)
  File "/app/new_sparrow/sparrow/sparrow-data/parse/sparrow_parse/extractors/vllm_extractor.py", line 137, in _run_model_inference
    result = model_inference_instance.inference(input_data)[0]
  File "/app/new_sparrow/sparrow/sparrow-data/parse/sparrow_parse/vllm/mlx_inference.py", line 108, in inference
    prompt = apply_chat_template(processor, config, messages)  # Assuming defined
  File "/usr/local/lib/python3.10/site-packages/mlx_vlm/prompt_utils.py", line 35, in apply_chat_template
    message = get_message_json(config["model_type"], prompt)
TypeError: 'ModelConfig' object is not subscriptable

**Comment by preethisenthil27** [comment]
> when i run python -m sparrow_parse.extractors.vllm_extractor
> 
> im facing this issue
> 
> root@cw-ai-gpu-01:/app/new_sparrow/sparrow/sparrow-data/parse# python -m sparrow_parse.extractors.vllm_extractor MLXInference initialized with model: mlx-community/Qwen2-VL-72B-Instruct-4bit Input data: [ { 'file_path': '/app/new_sparrow/sparrow/sparrow-data/Pdf/finalcial_doc.pdf', 'text_input': 'retrieve document data. return response in JSON format' } ] Processing 6 pages for table extraction. Loading table detection model... Table detection model initialized. Preparing image for table detection... Identifying tables in the image... Cropping tables from the image... Table detected in: /tmp/tmp0igfotwi/finalcial_doc_page_1.jpg - 1 Table detected in: /tmp/tmp0igfotwi/finalcial_doc_page_1.jpg - 2 Table detected in: /tmp/tmp0igfotwi/finalcial_doc_page_1.jpg - 3 Table detected in: /tmp/tmp0igfotwi/finalcial_doc_page_1.jpg - 4 Table detected in: /tmp/tmp0igfotwi/finalcial_doc_page_1.jpg - 5 Processing page_1_table_1 for document /tmp/tmp0igfotwi/finalcial_doc_page_1.jpg Fetching 18 files: 100%|███████████████████████████████████████████████████████| 18/18 [00:00<00:00, 3762.08it/s] Traceback (most recent call last): File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code exec(code, run_globals) File "/app/new_sparrow/sparrow/sparrow-data/parse/sparrow_parse/extractors/vllm_extractor.py", line 177, in results_array, num_pages = extractor.run_inference(model_inference_instance, input_data, tables_only=True, File "/app/new_sparrow/sparrow/sparrow-data/parse/sparrow_parse/extractors/vllm_extractor.py", line 30, in run_inference return self._process_pdf(model_inference_instance, input_data, tables_only, debug, debug_dir, mode) File "/app/new_sparrow/sparrow/sparrow-data/parse/sparrow_parse/extractors/vllm_extractor.py", line 43, in _process_pdf results = self._process_pages(model_inference_instance, output_files, input_data, tables_only, debug, debug_dir) File "/app/new_sparrow/sparrow/sparrow-data/parse/sparrow_parse/extractors/vllm_extractor.py", line 84, in _process_pages tables_result = self._extract_tables( File "/app/new_sparrow/sparrow/sparrow-data/parse/sparrow_parse/extractors/vllm_extractor.py", line 117, in _extract_tables result = self._run_model_inference(model_inference_instance, input_data) File "/app/new_sparrow/sparrow/sparrow-data/parse/sparrow_parse/extractors/vllm_extractor.py", line 137, in _run_model_inference result = model_inference_instance.inference(input_data)[0] File "/app/new_sparrow/sparrow/sparrow-data/parse/sparrow_parse/vllm/mlx_inference.py", line 108, in inference prompt = apply_chat_template(processor, config, messages) # Assuming defined File "/usr/local/lib/python3.10/site-packages/mlx_vlm/prompt_utils.py", line 35, in apply_chat_template message = get_message_json(config["model_type"], prompt) TypeError: 'ModelConfig' object is not subscriptable

same issue ;- TypeError: 'ModelConfig' object is not subscriptable

**Comment by abaranovskis-redsamurai** [comment]
Based on stack trace, error from MLX-VLM. Try to run MLX-VLM directly for debug purpose, see readme here: https://github.com/Blaizzy/mlx-vlm

**Comment by preethisenthil27** [comment]
I have checked the repo 
there the  " mlx_vlm/prompt_utils.py "  which is a file which sets up when we use command "pip install mlx-vlm"
in this repo they have made lots of changes, might be to adjust many models
 and made changes in many default files when installed 
 
 i have tried re-installing mlx-vllm to confirm for any updations 
 so it would be helpful if you could provide your insight on what changed to make in mlx-vlm default packages.

**Comment by abaranovskis-redsamurai** [comment]
It works without any issues on my M4 machine, with mlx-vlm==0.1.4 as per requirements file. So, I can't really help you much.

**Comment by preethisenthil27** [comment]
this is actually my prompt_utils.py
def get_message_json(model_name, prompt):
    """
    Get the appropriate JSON message based on the specified model.

    Args:
        model_name (str): The model for which to generate the message.
        prompt (str): The text prompt to be included in the message.
        *args: Additional positional arguments (unused).
        **kwargs: Additional keyword arguments (unused).

    Returns:
        dict: A dictionary representing the JSON message for the specified model.
    """
    if model_name.lower() in ["idefics2", "qwen2_vl"]:
        message = {
            "role": "user",
            "content": [{"type": "image"}, {"type": "text", "text": prompt}],
        }

    elif model_name.lower() in ["llava-qwen2", "llava", "llava_next", "bunny-llama"]:
        message = {"role": "user", "content": f"<image>\n{prompt}"}
    elif model_name.lower() == "phi3_v":
        message = {"role": "user", "content": f"<|image_1|>\n{prompt}"}
 elif model_name.lower() == "multi_modality":
        message = {"role": "user", "content": f"<image>{prompt}"}
    elif model_name.lower() == "paligemma":
        message = prompt
    else:
        raise ValueError(f"Unsupported model: {model_name}")

    return message


def apply_chat_template(processor, config, prompt):
    message = get_message_json(config["model_type"], prompt)

    if "chat_template" in processor.__dict__.keys():
        return processor.apply_chat_template(
            [message],
            tokenize=False,
            add_generation_prompt=True,
        )
elif "tokenizer" in processor.__dict__.keys():
        return processor.tokenizer.apply_chat_template(
            [message],
            tokenize=False,
            add_generation_prompt=True,
        )

    else:
        raise ValueError(
            "Error: processor does not have 'chat_template' or 'tokenizer' attribute."
        )
        
        Note :- no changes made by me
