### ISSUE TITLE
Sparrow logo - No technical issue 

### ISSUE THREAD

**Issue by ghazirecinov** [katanaml/sparrow#8]
Hi Commity , First of all I'd like to thank you for this amazing tool that helps me a lot to annotate unstructured data, For now I don't have any technical issue but for my final studies I'm preparing a presentation to show my approach using sparrow to annotate my custom data then refining the Donut model. All I need is the sparrow logo :P I can't find it anywhere. 
Thanks in advance

**Comment by abaranovskis-redsamurai** [comment]
hey, thanks for your feedback. I will add a logo in a day or two. I will update you here.

**Comment by ghazirecinov** [comment]
Thank you...

**Comment by abaranovskis-redsamurai** [comment]
Hi. I added logos into the assets folder here: https://github.com/katanaml/sparrow/tree/main/sparrow-ui/assets Feel free to use them.
