### ISSUE TITLE
extraction Invalid sparrow key error

### ISSUE THREAD

**Issue by dani-lu** [katanaml/sparrow#9]
I already installed the application through the docker method and the normal streamlit run method and I don't know what I'm doing wrong but when I try to execute the extraction for a given document it gives me this error:

{
"error":"Invalid Sparrow key."
}

Also I can't delete or create any labels or groups in the setup section.

Thanks for all your work.

**Comment by abaranovskis-redsamurai** [comment]
Hi. If you run it on your on infra, you can set your own value to sparrow_key. Simply set your own value in config.py from sparrow-ui and set the same value in config.py from sparrow-ml.

I tested, create/delete groups/labels from UI works fine. Are you getting any error in the log? As a workaround you can always add data in JSON directly, check labels.json and groups.json in docs folder.

**Comment by dani-lu** [comment]
thanks for your fast response I really appreciate it.

Im getting all of this from the log when I try to create or delete groups or labels: 

Received from Streamlit: {"buttons":{"create":false,"delete":false,"save":false},"default":null,"key":"toolbar_buttons_labels"}
DevTools failed to load source map: Could not load content for http://0.0.0.0:7860/component/st_aggrid.agGrid/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
VM18 main.3d60143d.js:2 flag allow_unsafe_jscode is on.
value @ VM18 main.3d60143d.js:2
r @ VM18 main.3d60143d.js:2
Ui @ VM18 main.3d60143d.js:2
xs @ VM18 main.3d60143d.js:2
El @ VM18 main.3d60143d.js:2
Cu @ VM18 main.3d60143d.js:2
yu @ VM18 main.3d60143d.js:2
vu @ VM18 main.3d60143d.js:2
ou @ VM18 main.3d60143d.js:2
S @ VM18 main.3d60143d.js:2
D @ VM18 main.3d60143d.js:2
VM18 main.3d60143d.js:2 AG Grid: invalid gridOptions property 'preSelectAllRows' did you mean any of these: suppressExpandablePivotGroups, suppressCellSelection, suppressRowDeselection, serverSideFilterAllLevels, suppressMiddleClickScrolls, suppressRowClickSelection, suppressClearOnFillReduction, suppressMultiRangeSelection
(anonymous) @ VM18 main.3d60143d.js:2
(anonymous) @ VM18 main.3d60143d.js:2
k @ VM18 main.3d60143d.js:2
e.checkProperties @ VM18 main.3d60143d.js:2
e.checkGridOptionsProperties @ VM18 main.3d60143d.js:2
e.init @ VM18 main.3d60143d.js:2
(anonymous) @ VM18 main.3d60143d.js:2
e.callLifeCycleMethodsOnBean @ VM18 main.3d60143d.js:2
(anonymous) @ VM18 main.3d60143d.js:2
e.callLifeCycleMethods @ VM18 main.3d60143d.js:2
e.wireBeans @ VM18 main.3d60143d.js:2
e @ VM18 main.3d60143d.js:2
e.create @ VM18 main.3d60143d.js:2
value @ VM18 main.3d60143d.js:2
bl @ VM18 main.3d60143d.js:2
Cl @ VM18 main.3d60143d.js:2
ml @ VM18 main.3d60143d.js:2
(anonymous) @ VM18 main.3d60143d.js:2
wu @ VM18 main.3d60143d.js:2
ou @ VM18 main.3d60143d.js:2
S @ VM18 main.3d60143d.js:2
D @ VM18 main.3d60143d.js:2
VM18 main.3d60143d.js:2 AG Grid: to see all the valid gridOptions properties please check: https://www.ag-grid.com/javascript-data-grid/grid-options/
e.checkProperties @ VM18 main.3d60143d.js:2
e.checkGridOptionsProperties @ VM18 main.3d60143d.js:2
e.init @ VM18 main.3d60143d.js:2
(anonymous) @ VM18 main.3d60143d.js:2
e.callLifeCycleMethodsOnBean @ VM18 main.3d60143d.js:2
(anonymous) @ VM18 main.3d60143d.js:2
e.callLifeCycleMethods @ VM18 main.3d60143d.js:2
e.wireBeans @ VM18 main.3d60143d.js:2
e @ VM18 main.3d60143d.js:2
e.create @ VM18 main.3d60143d.js:2
value @ VM18 main.3d60143d.js:2
bl @ VM18 main.3d60143d.js:2
Cl @ VM18 main.3d60143d.js:2
ml @ VM18 main.3d60143d.js:2
(anonymous) @ VM18 main.3d60143d.js:2
wu @ VM18 main.3d60143d.js:2
ou @ VM18 main.3d60143d.js:2
S @ VM18 main.3d60143d.js:2
D @ VM18 main.3d60143d.js:2
index.html?streamlitUrl=http%3A%2F%2F0.0.0.0%3A7860%2F:60 _sendMessage data: {"value":{"action":"create","timestamp":1686072496979},"dataType":"json"}
index.html?streamlitUrl=http%3A%2F%2F0.0.0.0%3A7860%2F:61 _sendMessage outboundData: {"isStreamlitMessage":true,"type":"streamlit:setComponentValue","value":{"action":"create","timestamp":1686072496979},"dataType":"json"}
index.html?streamlitUrl=http%3A%2F%2F0.0.0.0%3A7860%2F:138 Received from Streamlit: {"buttons":{"create":false,"delete":false,"save":false},"default":null,"key":"toolbar_buttons_labels"}
index.html:1 An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
AgGrid.tsx:270 flag allow_unsafe_jscode is on.
value @ AgGrid.tsx:270
r @ AgGrid.tsx:259
Ui @ react-dom.production.min.js:147
xs @ react-dom.production.min.js:198
El @ react-dom.production.min.js:292
Cu @ react-dom.production.min.js:280
yu @ react-dom.production.min.js:280
vu @ react-dom.production.min.js:280
ou @ react-dom.production.min.js:268
S @ scheduler.production.min.js:13
D @ scheduler.production.min.js:14
gridOptionsValidator.js:167 AG Grid: invalid gridOptions property 'preSelectAllRows' did you mean any of these: suppressExpandablePivotGroups, suppressCellSelection, suppressRowDeselection, serverSideFilterAllLevels, suppressMiddleClickScrolls, suppressRowClickSelection, suppressClearOnFillReduction, suppressMultiRangeSelection
(anonymous) @ gridOptionsValidator.js:167
(anonymous) @ object.js:16
k @ object.js:16
e.checkProperties @ gridOptionsValidator.js:166
e.checkGridOptionsProperties @ gridOptionsValidator.js:162
e.init @ gridOptionsValidator.js:89
(anonymous) @ context.js:202
e.callLifeCycleMethodsOnBean @ context.js:202
(anonymous) @ context.js:185
e.callLifeCycleMethods @ context.js:185
e.wireBeans @ context.js:64
e @ context.js:42
e.create @ grid.js:162
value @ agGridReactUi.tsx:114
bl @ react-dom.production.min.js:261
Cl @ react-dom.production.min.js:260
ml @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
wu @ react-dom.production.min.js:281
ou @ react-dom.production.min.js:270
S @ scheduler.production.min.js:13
D @ scheduler.production.min.js:14
gridOptionsValidator.js:170 AG Grid: to see all the valid gridOptions properties please check: https://www.ag-grid.com/javascript-data-grid/grid-options/
e.checkProperties @ gridOptionsValidator.js:170
e.checkGridOptionsProperties @ gridOptionsValidator.js:162
e.init @ gridOptionsValidator.js:89
(anonymous) @ context.js:202
e.callLifeCycleMethodsOnBean @ context.js:202
(anonymous) @ context.js:185
e.callLifeCycleMethods @ context.js:185
e.wireBeans @ context.js:64
e @ context.js:42
e.create @ grid.js:162
value @ agGridReactUi.tsx:114
bl @ react-dom.production.min.js:261
Cl @ react-dom.production.min.js:260
ml @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
wu @ react-dom.production.min.js:281
ou @ react-dom.production.min.js:270
S @ scheduler.production.min.js:13
D @ scheduler.production.min.js:14
DevTools failed to load source map: Could not load content for http://0.0.0.0:7860/component/st_aggrid.agGrid/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

I tested in Chrome and Safari and both had the same issue, sorry for the long message

**Comment by abaranovskis-redsamurai** [comment]
It looks like problem with Aggrid library. I updated requirements.txt to include the version I'm using:

streamlit-aggrid==0.3.3

Try with this version.

**Comment by dani-lu** [comment]
First of all, thanks for your quick response, I really appreciate it.

Setting the sparrow_key like you told seems to fix the create and deleting labels, but it stills giving me the same "Invalid Sparrow key." error when I try to extract information from any document from the inference tab, is this sparrow key some api_key you have to provide in order to be a valid one, and if so, where I can get it?

thank you very much.

**Comment by abaranovskis-redsamurai** [comment]
Ok, I got it. You get this error, because API URL points to our Hugging Face Spaces instance. You should change API URL to point to your own Sparrow ML service (where you set your own key). In Sparrow UI, go to views/data_inference.py, go to function render_results and change API URL there.

Hope it works now.

**Comment by dani-lu** [comment]
Yes!, it's all working now, thank you very much!

**Comment by Harshitdy** [comment]
Hey @abaranovskis-redsamurai! I'm very new to it and getting same error can you elaborate how to solve it.

**Comment by abaranovskis-redsamurai** [comment]
> Hey @abaranovskis-redsamurai! I'm very new to it and getting same error can you elaborate how to solve it.

Sparrow Key is used to control access to the API. But if you run the code locally you can set your own Sparrow Key as you wish. Just replace it with your own value as described above. If you run Sparrow UI and want to test inference, make sure to change API URL to point to your local instance (see description above)
